sheets:
  credentials_file: service-account.json
  source_spreadsheet_id: 1J7lKAKg-tyNhRU12nN0W2UvF3VK6i30nUj41nzqhpvw
  source_sheet_name: '2025'
  source_sheet_gid: 1677757368
  target_spreadsheet_id: 1OQAA0NKLekLtfTliw5MQXQiCsFLlh2v93oUfn2OVEKE
  target_sheet_name: Status Review
columns:
  status: Статус
  comment: Комментарий к статусу
  completion_date: Дата завершения - прогноз/факт
  identifier: Наименование проекта
  project_manager: РП ПО
allowed_statuses:
  - Запланирован
  - Предпроект
  - Реализация
  - Внедрение
  - Завершен (АБ тест)
  - Завершен
  - Остановлен
  - Отменен
header_row: 1
data_start_row: 13
rules_text: |
  Правила, которым должны соответствовать статусы:
  Шаблон статуса
  =====
  ДД.ММ.ГГГГ или ДД-ММ-ГГГГ - дата статуса, обязательное поле, должна быть дата не ранее понедельника текущей недели 
  Выполнено:
    Что уже сделано на текущий момент?
    Указать информацию об основных событиях по проекту в прошлом с указанием даты, когда веха пройдена.
    Указать завершенные за последние 1-2 месяца ключевые вехи - ДД.ММ.ГГГГ или ММ.ГГГГ или ММММ YYYY
    Если дата смещалась - в скобках указать предыдущую дату и причину смещения
  
  Запланировано:
    В разделе «Запланировано» указываются и текущие и будущие события
    Ключевые вехи в пределах 1-2 месяцев после даты статуса подробно - до ДД.ММ.ГГГГ или ММ.ГГГГ или ММММ YYYY
    Ключевые вехи более чем через 1-2 месяца после даты статуса - укрупненно - до ДД.ММ.ГГГГ или ММ.ГГГГ или ММММ YYYY
    Должна быть указана плановая дата завершения текущей активности (кроме случаев, когда проект находится в стадии «Завершен» или «Завершен (АБ тест)» или «Отменен»)
    Если проект находится в стадии «Завершен» или «Завершен (АБ тест)» или «Отменен», то:
    - раздел «Запланировано» можно опустить
    - текущая активность в разделе «Запланировано» может отсутствовать
    Будущие события должны иметь указание на плановую дату завершения
    Плановая дата завершения указывается в зависимости от горизонта события:
      - Конкретная дата, если она внутри текущего месяца
      - Месяц в формате ММ.ГГГГ или ММММ YYYY
      - Квартал в формате Q1/Q2/Q3/Q4-ГГГГ
  
  Примечания (НЕ обязательный раздел, может отсутсвовать у любых проектов):
    В примечании указываем риски или критические изменения
    Переприоритизация проекта спонсором, невосполненное отсутствие ресурсов и т.д. с указанием причин
    Риски/проблемы проекта с указанием причин и способов митигации
  =====
  
  Пример правильного статуса:
  =====
  13.05.2025
  Выполнено:
  - собраны первичные требования - 01.04.2025
  - проработаны варианты реализации - 10.04.2025
  - проект утвержден на КФИ - 20.04.2025
  Запланировано: 
  - разработаны бизнес-требования - с 10.05.2025 до 25.05.2025
  - разработано арх. решение - до 05.06.2025
  - составлены спецификации разработки - до 30.06.2025
  - разработка - до 30.07.2025
  - внедрение - до 15.08.2025
  - проект завершен - 30.08.2025
  Примечания:
  - старт проекта смещен Спонсором - май 2025 (январь 2025 - переприоритизация)
  =====
  
llm:
  model_env: OPENAI_MODEL
  temperature: 0.0
  max_output_tokens: 10000
  max_retries: 3
  api_key_env: OPENAI_API_KEY
  base_url_env: OPENAI_BASE_URL
batch_size: 10
